name: Spring boot program execution

on: 
  push:
  workflow_dispatch: 

jobs: 
  echo-maven-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4.2.2
      - name: Setup java JDK
        uses: action/setup-java@4.7.0
        with:
          java-version: '17'
          distribution: 'microsoft'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
    
